### ISSUE TITLE
NullPointerException when providing org.influxdb.dto.Point.Builder.tag with null argument

### ISSUE THREAD

**Issue by Cyanide789** [influxdb/influxdb-java#110]
Dear Majst01,

First of all: thanks for coding this API; it has saved me a great deal of work to integerate an ETL application with InfluxDB.

However recently, I stumbled onto a nasty NullPointerException, which you may want to address:

19:54:35.452 [task-scheduler-2] WARN  <<anonymised_package_name>>.InfluxWriter - Could not write to InfluxDB server. Underlying exception is null
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
        at com.google.common.escape.ArrayBasedCharEscaper.escape(ArrayBasedCharEscaper.java:118)
        at org.influxdb.dto.Point.concatenatedTags(Point.java:246)
        at org.influxdb.dto.Point.lineProtocol(Point.java:236)
        at org.influxdb.dto.BatchPoints.lineProtocol(BatchPoints.java:256)
        at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:163)
        at <<anonymised_package_name>>.InfluxWriter.write(VisInfluxWriter.java:85)

I caused this (by mistake) by setting a null tag in a PointBuilder, so org.influxdb.dto.Point.Builder.tag("description", null). Now you may argue if it isn't the responsibility of the implementor to make sure this never happens, but many public APIs do null-checks and return customised error messages for it.

Just thought I'd let you know.

Kind regards,
Cyanide789

**Comment by majst01** [comment]
closed by #136
