### ISSUE TITLE
Unable to run tests for this repo

### ISSUE THREAD

**Issue by slomek** [influxdb/influxdb-java#124]
I wanted to contribute, but I'm having trouble running tests and can't start your docker image:

**docker**:

    $ docker run --rm -ti majst01/influxdb-java:latest /bin/bash
    Couldn't parse configuration file: config.sample.toml
    open config.sample.toml: no such file or directory

**mvn test**:

	$ mvn test
	[INFO] Scanning for projects...
	[INFO]                                                                         
	[INFO] ------------------------------------------------------------------------
	[INFO] Building influxdb java bindings 2.0-SNAPSHOT
	[INFO] ------------------------------------------------------------------------
	[INFO] 
	[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ influxdb-java ---
	[INFO] 
	[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ influxdb-java ---
	[INFO] Using 'UTF-8' encoding to copy filtered resources.
	[INFO] skip non existing resourceDirectory /opt/workspace/influxdb-java/src/main/resources
	[INFO] 
	[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ influxdb-java ---
	[INFO] Nothing to compile - all classes are up to date
	[INFO] 
	[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ influxdb-java ---
	[INFO] Using 'UTF-8' encoding to copy filtered resources.
	[INFO] skip non existing resourceDirectory /opt/workspace/influxdb-java/src/test/resources
	[INFO] 
	[INFO] --- maven-compiler-plugin:2.0.2:testCompile (default-testCompile) @ influxdb-java ---
	[INFO] Nothing to compile - all classes are up to date
	[INFO] 
	[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ influxdb-java ---
	[INFO] Surefire report directory: /opt/workspace/influxdb-java/target/surefire-reports

	-------------------------------------------------------
	 T E S T S
	-------------------------------------------------------
	Running TestSuite
	retrofit.RetrofitError: Connection refused
		at retrofit.RetrofitError.networkError(RetrofitError.java:27)
		at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
		at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
		at org.influxdb.impl.$Proxy19.ping(Unknown Source)

**Comment by slomek** [comment]
Ok nevermind with running Docker - I'm a newbie with it and just figured it out. I have another issue now:

I have docker container up and running (can access console at :8083 and get 404 errors from :8086), but some tests still fail:

	$ mvn test
	[INFO] Scanning for projects...
	[INFO]                                                                         
	[INFO] ------------------------------------------------------------------------
	[INFO] Building influxdb java bindings 2.0-SNAPSHOT
	[INFO] ------------------------------------------------------------------------
	[INFO] 
	[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ influxdb-java ---
	[INFO] 
	[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ influxdb-java ---
	[INFO] Using 'UTF-8' encoding to copy filtered resources.
	[INFO] skip non existing resourceDirectory /opt/workspace/influxdb-java/src/main/resources
	[INFO] 
	[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ influxdb-java ---
	[INFO] Nothing to compile - all classes are up to date
	[INFO] 
	[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ influxdb-java ---
	[INFO] Using 'UTF-8' encoding to copy filtered resources.
	[INFO] skip non existing resourceDirectory /opt/workspace/influxdb-java/src/test/resources
	[INFO] 
	[INFO] --- maven-compiler-plugin:2.0.2:testCompile (default-testCompile) @ influxdb-java ---
	[INFO] Nothing to compile - all classes are up to date
	[INFO] 
	[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ influxdb-java ---
	[INFO] Surefire report directory: /opt/workspace/influxdb-java/target/surefire-reports

	-------------------------------------------------------
	 T E S T S
	-------------------------------------------------------
	Running TestSuite
	Pong{version=InfluxDB v0.8.3 (git: fbf9a47) (leveldb: 1.15), responseTime=180}
	##################################################################################
	---> HTTP GET http://127.0.0.1:8086/ping
	---> END HTTP (no body)
	<--- HTTP 200 http://127.0.0.1:8086/ping (1ms)
	Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
	Access-Control-Allow-Methods: GET, POST, PUT, DELETE
	Access-Control-Allow-Origin: *
	Access-Control-Max-Age: 2592000
	X-Influxdb-Version: InfluxDB v0.8.3 (git: fbf9a47) (leveldb: 1.15)
	Date: Sun, 29 Nov 2015 11:41:51 GMT
	Content-Type: application/x-gzip
	OkHttp-Selected-Protocol: http/1.1
	OkHttp-Sent-Millis: 1448797311591
	OkHttp-Received-Millis: 1448797311593

	{"status":"ok"}
	<--- END HTTP (15-byte body)
	#  Connected to InfluxDB Version: InfluxDB v0.8.3 (git: fbf9a47) (leveldb: 1.15) #
	##################################################################################
	---> HTTP GET http://127.0.0.1:8086/query?u=root&p=root&q=CREATE+DATABASE+IF+NOT+EXISTS+unittest_1448797311594
	---> END HTTP (no body)
	<--- HTTP 404 http://127.0.0.1:8086/query?u=root&p=root&q=CREATE+DATABASE+IF+NOT+EXISTS+unittest_1448797311594 (0ms)
	Content-Type: text/plain; charset=utf-8
	Date: Sun, 29 Nov 2015 11:41:51 GMT
	Content-Length: 19
	OkHttp-Selected-Protocol: http/1.1
	OkHttp-Sent-Millis: 1448797311596
	OkHttp-Received-Millis: 1448797311597

	404 page not found

	<--- END HTTP (19-byte body)
	---> HTTP GET http://127.0.0.1:8086/ping
	---> END HTTP (no body)
	<--- HTTP 200 http://127.0.0.1:8086/ping (0ms)
	Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
	Access-Control-Allow-Methods: GET, POST, PUT, DELETE
	Access-Control-Allow-Origin: *
	Access-Control-Max-Age: 2592000
	X-Influxdb-Version: InfluxDB v0.8.3 (git: fbf9a47) (leveldb: 1.15)
	Date: Sun, 29 Nov 2015 11:41:51 GMT
	Content-Type: application/x-gzip
	OkHttp-Selected-Protocol: http/1.1
	OkHttp-Sent-Millis: 1448797311599
	OkHttp-Received-Millis: 1448797311600

	{"status":"ok"}
	<--- END HTTP (15-byte body)
	---> HTTP GET http://127.0.0.1:8086/query?u=root&p=root&db=mydb&q=CREATE+DATABASE+mydb2
	---> END HTTP (no body)
	<--- HTTP 404 http://127.0.0.1:8086/query?u=root&p=root&db=mydb&q=CREATE+DATABASE+mydb2 (0ms)
	Content-Type: text/plain; charset=utf-8
	Date: Sun, 29 Nov 2015 11:41:51 GMT
	Content-Length: 19
	OkHttp-Selected-Protocol: http/1.1
	OkHttp-Sent-Millis: 1448797311602
	OkHttp-Received-Millis: 1448797311602

	404 page not found

	<--- END HTTP (19-byte body)
	---> HTTP GET http://127.0.0.1:8086/ping
	---> END HTTP (no body)
	<--- HTTP 200 http://127.0.0.1:8086/ping (1ms)
	Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
	Access-Control-Allow-Methods: GET, POST, PUT, DELETE
	Access-Control-Allow-Origin: *
	Access-Control-Max-Age: 2592000
	X-Influxdb-Version: InfluxDB v0.8.3 (git: fbf9a47) (leveldb: 1.15)
	Date: Sun, 29 Nov 2015 11:41:51 GMT
	Content-Type: application/x-gzip
	OkHttp-Selected-Protocol: http/1.1
	OkHttp-Sent-Millis: 1448797311604
	OkHttp-Received-Millis: 1448797311605

	{"status":"ok"}
	<--- END HTTP (15-byte body)
	---> HTTP GET http://127.0.0.1:8086/query?u=root&p=root&q=CREATE+DATABASE+IF+NOT+EXISTS+write_unittest_1448797311605
	---> END HTTP (no body)
	<--- HTTP 404 http://127.0.0.1:8086/query?u=root&p=root&q=CREATE+DATABASE+IF+NOT+EXISTS+write_unittest_1448797311605 (0ms)
	Content-Type: text/plain; charset=utf-8
	Date: Sun, 29 Nov 2015 11:41:51 GMT
	Content-Length: 19
	OkHttp-Selected-Protocol: http/1.1
	OkHttp-Sent-Millis: 1448797311606
	OkHttp-Received-Millis: 1448797311606

	404 page not found

	<--- END HTTP (19-byte body)
	Kill the Docker container
	[main] INFO org.mortbay.log - Logging to org.slf4j.impl.SimpleLogger(org.mortbay.log) via org.mortbay.log.Slf4jLog
	[1856158867@qtp-1787189503-1 - Acceptor0 DelayableSocketConnector@0.0.0.0:8080] ERROR WireMock - dispatch failed for {}
	Tests run: 13, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 5.312 sec <<< FAILURE!

**Comment by slomek** [comment]
Please ignore this, I somehow had my Dockerfile corrupted.
