### ISSUE TITLE
Running using JDK 1.6 causes to java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by evgenyf** [influxdb/influxdb-java#20]
java.lang.UnsupportedClassVersionError: com/squareup/okhttp/OkHttpClient : Unsupported major.minor version 51.0; Caused by: java.lang.UnsupportedClassVersionError: com/squareup/okhttp/OkHttpClient : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:421)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
        at org.influxdb.impl.InfluxDBImpl.<init>(InfluxDBImpl.java:72)
        at org.influxdb.InfluxDBFactory.connect(InfluxDBFactory.java:30)

**Comment by majst01** [comment]
Since https://github.com/square/okhttp/commit/cdd71f1bbd32f20d63d7100787b91c327d1b5b0c okhttp is Java 1.7. 

As Java 1.6 is in the unsupported mode, i really would stay with Java 1.7 as minimum requirement. If you cant update to 1.7 or newer for whatever reason, you can clone influxdb-java and lower the dependency to okhttpd to < 2.0 and see if this still works.

Greetings
Stefan

**Comment by evgenyf** [comment]
I've just tried to do it. Even with okhttp version 1.0.0 it stil does not work...Another okhttp's class causes to problem:
java.lang.UnsupportedClassVersionError: com/squareup/okhttp/internal/Util : Unsupported major.minor version 51.0

**Comment by majst01** [comment]
I guess you need to update your Runtime to Java 1.7 because replacing okhttp with something different which can run on old Java is a huge task.
I will on the other side update the pom to use 1.7 source and target in the near future anyway.

Sorry for that.

**Comment by evgenyf** [comment]
Thank you, I have to support JDK 1.6 ....

**Comment by majst01** [comment]
You can specify which http client to use in https://github.com/influxdb/influxdb-java/blob/master/src/main/java/org/influxdb/impl/InfluxDBImpl.java#L76 

If you remove the dependency to okhttp, retrofit will you the java httpurlconnection, you will loose some features as loadbalance and failover but gain java 1.6 compatibility.

hope this helps

**Comment by evgenyf** [comment]
Now I see both okhttp 1.6.0  and okhttp-urlconnection1.6.0 are working properly with JDK 1.6. It was my mistake in updating my war.
Thank you

**Comment by wqtty** [comment]
I forked and made it compatible with jdk 1.6 [here](https://github.com/wqtty/influxdb-java), hope it could help someone
