### ISSUE TITLE
retrofit.RetrofitError: Unexpected status line: w.onload = function () { 

### ISSUE THREAD

**Issue by zhuyuping** [influxdb/influxdb-java#23]
the bug  OkHttp?

retrofit.RetrofitError: Unexpected status line: w.onload = function () { 
	at retrofit.RetrofitError.networkError(RetrofitError.java:27)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:390)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at org.influxdb.impl.$Proxy75.write(Unknown Source)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:126)
	at com.zsuper.controller.HomeController.updatePriceAndBroadcast(HomeController.java:79)
	at com.zsuper.controller.HomeController.access$000(HomeController.java:56)
	at com.zsuper.controller.HomeController$1.run(HomeController.java:92)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.net.ProtocolException: Unexpected status line: w.onload = function () { 
	at com.squareup.okhttp.internal.http.StatusLine.parse(StatusLine.java:53)
	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:189)
	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:676)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:426)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:371)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:466)
	at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
	at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
	... 14 more
2015-02-13 21:13:48,852 ERROR pool-2-thread-1 org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
retrofit.RetrofitError: Unexpected status line: w.onload = function () { 
	at retrofit.RetrofitError.networkError(RetrofitError.java:27)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:390)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at org.influxdb.impl.$Proxy75.write(Unknown Source)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:126)
	at com.zsuper.controller.HomeController.updatePriceAndBroadcast(HomeController.java:79)
	at com.zsuper.controller.HomeController.access$000(HomeController.java:56)
	at com.zsuper.controller.HomeController$1.run(HomeController.java:92)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.net.ProtocolException: Unexpected status line: w.onload = function () { 
	at com.squareup.okhttp.internal.http.StatusLine.parse(StatusLine.java:53)
	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:189)
	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:676)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:426)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:371)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:466)
	at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
	at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
	... 14 more
2015-02-13 21:14:59,856 ERROR pool-2-thread-1 org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
retrofit.RetrofitError: Unexpected status line: w.onload = function () { 
	at retrofit.RetrofitError.networkError(RetrofitError.java:27)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:390)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at org.influxdb.impl.$Proxy75.write(Unknown Source)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:126)
	at com.zsuper.controller.HomeController.updatePriceAndBroadcast(HomeController.java:79)
	at com.zsuper.controller.HomeController.access$000(HomeController.java:56)
	at com.zsuper.controller.HomeController$1.run(HomeController.java:92)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.net.ProtocolException: Unexpected status line: w.onload = function () { 
	at com.squareup.okhttp.internal.http.StatusLine.parse(StatusLine.java:53)
	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:189)
	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:676)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:426)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:371)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:466)
	at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
	at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
	... 14 more

**Comment by majst01** [comment]
Hi zhuyuping,

are you sure your specified influxdb address is working ?
The error you pasted looks like okhttpd got a response from a webserver which is not influxdb.

Greetings

**Comment by majst01** [comment]
Any news from this ? Otherwise i will close this issue.

**Comment by zhuyuping** [comment]
This error occurs when the writing frequently use threads , and then does not seem to appear after I use apache common pool2

**Comment by zhuyuping** [comment]
my code  when  not use the common pool2 

@PostConstruct
	  private void broadcastTimePeriodically() {
	    scheduler.scheduleAtFixedRate(new Runnable() {
	      @Override public void run() {
	        //updatePriceAndBroadcast();
	    	    Integer rnx = rand.nextInt(10000);
	    	  	Serie serie = new Serie.Builder("testrandom")
	       		.columns("test3")
	       		.values(rnx)
	       		.build();
	    	
	    	     influxDB.write("db",  TimeUnit.MILLISECONDS, serie);
	      }
	    }, 1000);
	  }

**Comment by majst01** [comment]
Hi,

you are sure that you are not oversaturating the influxdb server ? Any logs from influxdb pointing to some errors ?

**Comment by zhuyuping** [comment]
Server does not appear wrong, just write in the client

**Comment by zhuyuping** [comment]
public class InfluxDBFactoryBean implements FactoryBean<InfluxDB>,InitializingBean{
	
	
	private String url;//地址
	
	private String username;//账号
	
	private String password;//密码
	
	
	
	


	public InfluxDBFactoryBean(String url, String username, String password) {
		super();
		this.url = url;
		this.username = username;
		this.password = password;
	}


	public void setUrl(String url) {
		this.url = url;
	}


	public void setUsername(String username) {
		this.username = username;
	}

	

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public InfluxDB getObject() throws Exception {
		
		return InfluxDBFactory.connect(url, username,password);
	}

	@Override
	public Class<?> getObjectType() {
		
		return InfluxDB.class;
	}

	@Override
	public boolean isSingleton() {
		
		return true;
	}


	@Override
	public void afterPropertiesSet() throws Exception {
	        
		
	}

}

**Comment by zhuyuping** [comment]
is Singleton cause?

**Comment by zhuyuping** [comment]
public class InfluxDBPoll extends  BasePooledObjectFactory<InfluxDB> implements   FactoryBean<GenericObjectPool>{
	
	
    private String url;//地址
	
	private String username;//账号
	
	private String password;//密码
	
	
	
	
	
	public InfluxDBPoll(String url, String username, String password) {
		super();
		this.url = url;
		this.username = username;
		this.password = password;
	}

	//http://commons.apache.org/proper/commons-pool/examples.html

	@Override
	public InfluxDB create() throws Exception {
		
		return InfluxDBFactory.connect(url, username,password);
	}

	@Override
	public PooledObject<InfluxDB> wrap(InfluxDB influxDB) {
		
		
		return new DefaultPooledObject<InfluxDB>(influxDB);
		
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public GenericObjectPool getObject() throws Exception {
		
		return new GenericObjectPool<InfluxDB>(new InfluxDBPoll(url, username, password));
	}

	@Override
	public Class<?> getObjectType() {
	
		return GenericObjectPool.class;
	}

	@Override
	public boolean isSingleton() {
		
		return true;
	}
	
	
	

}

**Comment by majst01** [comment]
Hi,

The Proble is that the Server you are talking to response with:
~~~~
Caused by: java.net.ProtocolException: Unexpected status line: w.onload = function () { 
~~~~

I guess you have a loadbalancer or a other L7 server between your influxdb client and Server, and this "Reverse Proxy" sometimes does not return a influxdb result. 
This might be because this "Reverse Proxy" hit some limits.
Just a wild guess.

**Comment by zhuyuping** [comment]
maybe
