### ISSUE TITLE
retrofit.RetrofitError: null

### ISSUE THREAD

**Issue by aniketalhat** [influxdb/influxdb-java#33]
Hi,
I just started to use InfluxDb(single node) to store system metrics using real time processing engine, Apache Storm. Everything was working really well before encountering this error. It even did not occurred when server was under heavy load but with normal traffic. Any insight ?

```
Caused by: retrofit.RetrofitError: null
        at retrofit.RetrofitError.networkError(RetrofitError.java:27) ~[stormjar.jar:na]
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:390) ~[stormjar.jar:na]
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[stormjar.jar:na]
        at org.influxdb.impl.$Proxy0.write(Unknown Source) ~[na:na]
        at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:126) ~[stormjar.jar:na]
Caused by: java.io.EOFException: null
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:154) ~[stormjar.jar:na]
        at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:189) ~[stormjar.jar:na]
        at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101) ~[stormjar.jar:na]
        at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:676) ~[stormjar.jar:na]
        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:426) ~[stormjar.jar:na]
        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:371) ~[stormjar.jar:na]
        at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:466) ~[stormjar.jar:na]
        at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73) ~[stormjar.jar:na]
        at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38) ~[stormjar.jar:na]
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321) ~[stormjar.jar:na]
        ... 22 common frames omitted
```
P.S I have removed unnecessary log lines.

**Comment by majst01** [comment]
Any update on this ? otherwise i will close this issue
