### ISSUE TITLE
InfluxDB.write NullPointerException

### ISSUE THREAD

**Issue by aosobov** [influxdb/influxdb-java#48]
Hi,

Using InfluxDB.write(final String database, final String retentionPolicy, final Point point) throws a NullPointerException when used with a valid database, retentionPolicy, and point.

Stack Trace:
java.lang.NullPointerException
	org.influxdb.impl.TimeUtil.toTimePrecision(TimeUtil.java:21)
	org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:155)
	org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:140)

It seems that the precision of the BatchPoints object is being accessed, but it is null as it is never set when the BatchPoints object is created (InfluxDBImpl.java:138).

I am using version 2.0.

Thanks
Anton

**Comment by majst01** [comment]
Hi Anton,

can you please pull the latest version and try to reproduce, i did a lot of fixes in the last few days regarding time and BatchPoints.

**Comment by aosobov** [comment]
Hi Stefan,

Thank you for the quick response. I just pulled master and the issue is now fixed. Do you have a timeline for the next release of the client and when it will be available in maven central?


Thanks,
Anton

**Comment by majst01** [comment]
The guy which did this in the past is actually on vacation, so please be patient.

**Comment by phantc67** [comment]
On influxdB version 1.4.2, I am learning how to write data from database to BlockingQueue and trying to run /src/test/java/org /influxdb /InfluxDBTest.java file. 
I got error on line 645 : this.influxDB.write(batchPoints).
Error: java.lang.NullPointerException. Can you help me with this issue? Thanks a lot.

**Comment by majst01** [comment]
InfluxDBTest.java is executed on every commit without any errors in the CI Pipeline from this script: https://github.com/influxdata/influxdb-java/blob/master/compile-and-test.sh .

If you encounter a NPE, this must be related to you way you are calling it, so please add some more details on how you are executing this test.

**Comment by phantc67** [comment]
Here is the code which was testing:

 @Test
  public void testChunking() throws InterruptedException {
    /*if (this.influxDB.version().startsWith("0.") || this.influxDB.version().startsWith("1.0")) {
      // do not test version 0.13 and 1.0
      return;
    }*/
   // String dbName = "write_unittest_" + System.currentTimeMillis();
   // this.influxDB.createDatabase(dbName);
    //String rp = TestUtis.defaultRetentionPolicy(this.influxDB.version());
    String rp = "Default";
    String dbName = "testChunking";
    BatchPoints batchPoints = BatchPoints.database(dbName).retentionPolicy(rp).build();
    Point point1 = Point.measurement("disk").tag("atag", "a").addField("used", 60L).addField("free", 1L).build();
    Point point2 = Point.measurement("disk").tag("atag", "b").addField("used", 70L).addField("free", 2L).build();
    Point point3 = Point.measurement("disk").tag("atag", "c").addField("used", 80L).addField("free", 3L).build();
    batchPoints.point(point1);
    batchPoints.point(point2);
    batchPoints.point(point3);
    System.out.print("====>> batchPoints : " + batchPoints);
    //this.influxDB.write(batchPoints);
    influxDB.write(batchPoints);  //<====== ERROR : 

ERROR: 
====>> batchPoints : BatchPoints [database=testChunking, retentionPolicy=Default, consistency=ONE, tags={}, points=[Point [name=disk, time=1514521190791, tags={atag=a}, precision=MILLISECONDS, fields={free=1, used=60}], Point [name=disk, time=1514521190791, tags={atag=b}, precision=MILLISECONDS, fields={free=2, used=70}], Point [name=disk, time=1514521190791, tags={atag=c}, precision=MILLISECONDS, fields={free=3, used=80}]]]
java.lang.NullPointerException
	at gms.shared.mechanisms.objectstoragedistribution.coi.waveforms.repository.influx.WaveformRepositoryInfluxDbTest.testChunking(WaveformRepositoryInfluxDbTest.java:213)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255

**Comment by majst01** [comment]
And can you show how you created the `influxDB` instance ?

**Comment by phantc67** [comment]
It works now when I declare this.influxdb = InfluxDBFactory.connect "http.....");
Now I'm testing how to fetch data from database into BlockingQueue. Do you know how to read data from BlockingQueue after fetching.? Thanks for your help. :)

**Comment by phantc67** [comment]
I got an error in java code. I think the syntax  to call secondSinceEpoch variable in WHERE clause is incorrect.

endTime = 1970-01-02T03:04:08.923Z

long secondSinceEpoch = endTime.getEpochSecond();
Query query = new Query("select * from RawWaveform where time=\'$secondSinceEpoch\'" , dbName);

==> error=invalid operation: time and *influxql.StringLiteral are not compatible

**Comment by majst01** [comment]
Please file separate issues for new threads.

you cant refer to java variables with $variablename in your influxql query !

**Comment by phantc67** [comment]
Everything is working now. Thanks for your help.
