### ISSUE TITLE
NPE in non-batch request when using latest (2.0) influxdb-java client

### ISSUE THREAD

**Issue by jpbetz** [influxdb/influxdb-java#61]
Attempted to use https://jitpack.io/#influxdb/influxdb-java/influxdb-java-2.0 to get access to the 2.0 client, but ran into this error:

```
Point point = Point.measurement("span")
        .time(span.timestamp, TimeUnit.MILLISECONDS);
        // ...

influxDB.write(dbName, "default", point);
```

results in:

```
java.lang.NullPointerException
	at org.influxdb.impl.TimeUtil.toTimePrecision(TimeUtil.java:21)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:155)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:140)
	at Consumer.Consumer$$handleEvent$1(Main.scala:72)
	at Consumer$$anonfun$run$1.apply(Main.scala:37)
	at Consumer$$anonfun$run$1.apply(Main.scala:34)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at Consumer.run(Main.scala:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ajsquared** [comment]
I'm also encountering this error.  It looks to me like it's ultimately still creating a BatchPoints object, and that object has a null precision.

**Comment by ajsquared** [comment]
I was able to work around it by using `b70c1adc38` as the version instead of `influxdb-java-2.0` to build the most recent commit to the repository.

**Comment by voukka** [comment]
@ajsquared  couple of tests fail at revision you mentioned `b70c1adc38`. At `526fe08` all tests passed and it seems to work too.

**Comment by majst01** [comment]
This issue seems to be resolved, closing now. Feel free to reopen if the problem still exists.
